services:
  # Consul service
  consul:
      image: consul:1.15.4
      container_name: consul
      ports:
      - "8500:8500"
      networks:
      - consul

  # Auth service
  auth-service:
    build:
        context: .
        dockerfile: cmd/auth/Dockerfile
    container_name: auth-service
    environment:
      DB: myuser:strongpass@tcp(auth-db:3306)/mydb?parseTime=true
    ports:
      - "4355:8080" # Rest
      - "8081:8081" # gRPC
    networks:
      - consul
      - auth
    depends_on:
      auth-db:
        condition: service_healthy

  auth-db:
    image: mysql:latest
    container_name: auth-db
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: strongpass
      MYSQL_ROOT_PASSWORD: verystrongpass
    ports:
      - "5677:3306"
    volumes:
      - auth_db_data:/var/lib/mysql
    networks:
        - auth
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  auth_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db/auth

networks:
    consul:
    auth: