services:
  # Auth service
  auth-http-service:
    build:
      context: .
      dockerfile: cmd/auth/http/Dockerfile
    container_name: auth-http-service
    environment:
      DB: myuser:strongpass@tcp(auth-db:3306)/mydb?parseTime=true
      PORT: 8080
      HASH_SALT: "hashSalt"
      JWT_SECRET: "accessPass"
      JWT_REFRESH: "refreshPass"
      USER_SERVICE_HTTP_ADDR: user-http-service:8082
      USER_SERVICE_GRPC_ADDR: user-grpc-service:8083
    ports:
      - "8080:8080"
    networks:
      - services
      - auth
    depends_on:
      auth-db:
        condition: service_healthy

  auth-grpc-service:
    build:
      context: .
      dockerfile: cmd/auth/grpc/Dockerfile
    container_name: auth-grpc-service
    environment:
      DB: myuser:strongpass@tcp(auth-db:3306)/mydb?parseTime=true
      PORT: 8081
      HASH_SALT: "hashSalt"
      JWT_SECRET: "accessPass"
      JWT_REFRESH: "refreshPass"
      USER_SERVICE_HTTP_ADDR: user-http-service:8082
      USER_SERVICE_GRPC_ADDR: user-grpc-service:8083
    ports:
      - "8081:8081"
    networks:
      - services
      - auth
    depends_on:
      auth-db:
        condition: service_healthy

  auth-db:
    image: mysql:latest
    container_name: auth-db
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: strongpass
      MYSQL_ROOT_PASSWORD: verystrongpass
    ports:
      - "5677:3306"
    volumes:
      - auth_db_data:/var/lib/mysql
    networks:
        - auth
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  user-service:
    build:
        context: .
        dockerfile: cmd/user/Dockerfile
    container_name: user-service
    environment:
        DB: myuser:strongpass@tcp(user-db:3306)/mydb?parseTime=true
        DISCOVERY_ADDR: consul:8500
        EXTERNAL_REST_PORT: 8082
        EXTERNAL_GRPC_PORT: 8083
    ports:
      - "8082:8080" # Rest
      - "8083:8081" # gRPC
    networks:
        - consul
        - user
    depends_on:
      user-db:
        condition: service_healthy

  user-db:
    image: mysql:latest
    container_name: user-db
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: strongpass
      MYSQL_ROOT_PASSWORD: verystrongpass
    ports:
      - "5678:3306"
    volumes:
      - user_db_data:/var/lib/mysql
    networks:
        - user
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  auth_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db/auth
  user_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db/user

networks:
    consul:
    auth:
    user: