basePath: /api/v1
definitions:
  echo.HTTPError:
    properties:
      message: {}
    type: object
  internal_auth_transport_rest_v1.accessTokenResp:
    properties:
      token:
        type: string
    type: object
  internal_auth_transport_rest_v1.userAuthenticateResp:
    properties:
      user_id:
        type: integer
    type: object
  internal_auth_transport_rest_v1.userChangePasswordReq:
    properties:
      password:
        type: string
    required:
    - password
    type: object
  internal_auth_transport_rest_v1.userInfoResp:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      updated_at:
        type: string
      username:
        type: string
    type: object
  internal_auth_transport_rest_v1.userLoginReq:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  internal_auth_transport_rest_v1.userRegisterReq:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  internal_auth_transport_rest_v1.userRegisterResp:
    properties:
      activation_token:
        type: string
    type: object
  v1.getUserResponse:
    properties:
      avatar:
        type: string
      nickname:
        type: string
      role:
        type: integer
      user_id:
        type: integer
      username:
        type: string
    type: object
  v1.putUserRequest:
    properties:
      email:
        type: string
      nickname:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Twitter Auth Service
  title: Twitter Auth Service
  version: "1.0"
paths:
  /{userID}:
    delete:
      consumes:
      - application/json
      description: Delete user
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: integer
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Delete user
      tags:
      - user
    put:
      consumes:
      - application/json
      description: Update user
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: integer
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.putUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Update user
      tags:
      - user
  /{username}:
    get:
      consumes:
      - application/json
      description: Get user by username
      parameters:
      - description: Username
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.getUserResponse'
      summary: Get user by username
      tags:
      - user
  /activate/{token}:
    get:
      description: Activate user
      parameters:
      - description: activation token
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Set-Cookie:
              description: Refresh Token
              type: string
          schema:
            $ref: '#/definitions/internal_auth_transport_rest_v1.accessTokenResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Activate
      tags:
      - User
  /authenticate:
    get:
      description: Check user access token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_auth_transport_rest_v1.userAuthenticateResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/echo.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: Authenticate
      tags:
      - User
  /change/password:
    patch:
      consumes:
      - application/json
      description: Change user password
      parameters:
      - description: new password
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_auth_transport_rest_v1.userChangePasswordReq'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        default:
          description: ""
          schema:
            $ref: '#/definitions/echo.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: Change Password
      tags:
      - User
  /info:
    get:
      description: Get users info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_auth_transport_rest_v1.userInfoResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/echo.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: Info
      tags:
      - User
  /login:
    post:
      consumes:
      - application/json
      description: login bruh
      parameters:
      - description: user credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_auth_transport_rest_v1.userLoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Set-Cookie:
              description: Refresh Token
              type: string
          schema:
            $ref: '#/definitions/internal_auth_transport_rest_v1.accessTokenResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: User login
      tags:
      - User
  /refresh:
    post:
      consumes:
      - application/json
      description: Refresh jwt token
      parameters:
      - description: Refresh Token
        in: header
        name: refresh_token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Set-Cookie:
              description: Refresh Token
              type: string
          schema:
            $ref: '#/definitions/internal_auth_transport_rest_v1.accessTokenResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Refresh token
      tags:
      - Token
  /register:
    post:
      consumes:
      - application/json
      description: reg bruh
      parameters:
      - description: user credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_auth_transport_rest_v1.userRegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_auth_transport_rest_v1.userRegisterResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: User register
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
