httpServer:
  bodyLimit: 20MB
  allowedOrigins:
    - "*"

grpcServer:

jwt:
  tokenDuration: 5m
  refreshDuration: 168h # 7 days

validator:
  emailRegex: "^[a-z0-9._%+\\-]+@[a-z0-9.\\-]+\\.[a-z]{2,4}$"
  usernameRegex: "^[a-zA-Z0-9]{3,20}$"
  passwordRegex: "^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$"