basePath: /api/v1
definitions:
  echo.HTTPError:
    properties:
      message: {}
    type: object
  internal_transport_rest_v1.refreshTokenReq:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  internal_transport_rest_v1.tokensResp:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  internal_transport_rest_v1.userAuthenticateResp:
    properties:
      user_id:
        type: integer
    type: object
  internal_transport_rest_v1.userChangeEmailReq:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  internal_transport_rest_v1.userChangePasswordReq:
    properties:
      password:
        type: string
    required:
    - password
    type: object
  internal_transport_rest_v1.userChangeUsernameReq:
    properties:
      username:
        type: string
    required:
    - username
    type: object
  internal_transport_rest_v1.userInfoResp:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      updated_at:
        type: string
      username:
        type: string
    type: object
  internal_transport_rest_v1.userLoginReq:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  internal_transport_rest_v1.userRegisterReq:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  internal_transport_rest_v1.userRegisterResp:
    properties:
      activation_token:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Bombaclac
  title: Twitter Auth Service
  version: "1.0"
paths:
  /activate/{token}:
    get:
      description: Activate user
      parameters:
      - description: activation token
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_transport_rest_v1.tokensResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Activate
      tags:
      - User
  /authenticate:
    get:
      description: Check user access token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_transport_rest_v1.userAuthenticateResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/echo.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: Authenticate
      tags:
      - User
  /change/email:
    post:
      consumes:
      - application/json
      description: Change user email
      parameters:
      - description: new email
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_transport_rest_v1.userChangeEmailReq'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        default:
          description: ""
          schema:
            $ref: '#/definitions/echo.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: Change Email
      tags:
      - User
  /change/password:
    post:
      consumes:
      - application/json
      description: Change user password
      parameters:
      - description: new password
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_transport_rest_v1.userChangePasswordReq'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        default:
          description: ""
          schema:
            $ref: '#/definitions/echo.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: Change Password
      tags:
      - User
  /change/username:
    post:
      consumes:
      - application/json
      description: Change user username
      parameters:
      - description: new username
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_transport_rest_v1.userChangeUsernameReq'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        default:
          description: ""
          schema:
            $ref: '#/definitions/echo.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: Change Username
      tags:
      - User
  /info:
    get:
      description: Get users info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_transport_rest_v1.userInfoResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/echo.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: Info
      tags:
      - User
  /login:
    post:
      consumes:
      - application/json
      description: login bruh
      parameters:
      - description: user credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_transport_rest_v1.userLoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_transport_rest_v1.tokensResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: User login
      tags:
      - User
  /refresh:
    post:
      consumes:
      - application/json
      description: Refresh jwt token
      parameters:
      - description: refresh token
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_transport_rest_v1.refreshTokenReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_transport_rest_v1.tokensResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Refresh token
      tags:
      - Token
  /register:
    post:
      consumes:
      - application/json
      description: reg bruh
      parameters:
      - description: user credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_transport_rest_v1.userRegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_transport_rest_v1.userRegisterResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: User register
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
